### PR TITLE
Revert "Update CHANGELOG.rst"

### PR DESCRIPTION
**Pull request by ayrton04**
Reverts locusrobotics/robot_localization#9

### CODE REVIEW

**Comment by bradleypowers** [comment]
This seems fine.  Do you still want to merge this in?  If so, go ahead.

**Comment by ayrton04** [comment]
Ha, no, sorry. This was me trying to get the stupid build server to detect PRs.

**Comment by bradleypowers** [comment]
Do we need to keep this open?

**Comment by ayrton04** [comment]
If it's especially irritating to see it in the list, then no. I will likely resume doing this at some point so I can test PR-triggered Jenkins builds.

**Comment by bradleypowers** [comment]
That's fine.  It's not *especially* irritating, I'll just keep checking it and asking you about it :)

**Pull request closed without merging**
